//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stajpaylasim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public int DId { get; set; }
        public string DDesc { get; set; }
        public string DName { get; set; }
        public string DURL { get; set; }
        public Nullable<int> TId { get; set; }
        public Nullable<int> SId { get; set; }
        public Nullable<int> DTId { get; set; }
        public Nullable<int> DSId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
